import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      {/* IGNORAR HEAD */}
      <Head>
        <title>Handy Volunteers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black text-white">
        TESTE
      </div>
      {/* IGNORAR HEAD */}
      {/* bg - background / text - cor do texto */}
      <div className="bg-blue-600 text-red-500">
        TESTE
      </div>
      {/* se quiser uma cor diferente, seja de fundo ou do texto, que não seja red, blue, 
      entre todas as outras, usar colchetes e a cor em Hexadecimal, text-[#cor] ou bg-[#cor] */}
      <div className='text-[#afa031] bg-[#031323]'>essa é uma div com uma cor que eu defini</div>
    </>
  )
}
